version: '3'
services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha_hireiq
    restart: always
    ports:
      - "3001:3000"
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WAHA_LOG_LEVEL=info
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=admin
      - WHATSAPP_SWAGGER_USERNAME=admin
      - WHATSAPP_SWAGGER_PASSWORD=admin
      - WAHA_API_KEY=hireiq_secret_key
